import { pgTable, uuid, varchar, text, timestamp, date, jsonb } from "drizzle-orm/pg-core";

export const members = pgTable("members", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: varchar("name", { length: 50 }).notNull(),
  phone: varchar("phone", { length: 20 }),
  address: varchar("address", { length: 300 }),
  detailAddress: varchar("detail_address", { length: 200 }),
  birthDate: date("birth_date"),
  gender: varchar("gender", { length: 10 }),
  position: varchar("position", { length: 30 }).default("성도"),
  department: varchar("department", { length: 50 }),
  district: varchar("district", { length: 50 }),
  familyMembers: text("family_members").array().default([]).notNull(),
  familyHead: varchar("family_head", { length: 50 }),
  relationship: varchar("relationship", { length: 20 }),
  baptismDate: date("baptism_date"),
  baptismType: varchar("baptism_type", { length: 20 }),
  baptismChurch: varchar("baptism_church", { length: 100 }),
  registrationDate: date("registration_date"),
  memberJoinDate: date("member_join_date"),
  carNumber: varchar("car_number", { length: 20 }),
  notes: text("notes"),
  photoUrl: text("photo_url"),
  memberStatus: varchar("member_status", { length: 10 }).default("활동").notNull(),
  prayerRequests: jsonb("prayer_requests").default([]).notNull(),
  pastoralVisits: jsonb("pastoral_visits").default([]).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
